name: Hello world

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print build job
        run: echo "This is build job"

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Print test job
        run: echo "This is test job"

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Print deploy job
        run: echo "This is deploy job"

